folder: 'assets'
templates:
  -
    name: 'index'
    templ_type: 0
  -
    name: 'top'
    templ_type: 1
  -
    name: 'product_lst'
    templ_type: 3
  -
    name: 'product'
    templ_type: 2
  -
    name: 'shopkeeper'
    templ_type: 4
  -
    name: 'product_srh'
    templ_type: 5
  -
    name: 'option_stock'
    templ_type: 6
  -
    name: 'privacy'
    templ_type: 7
